sudo: false
language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - extra-android-m2repository
env:
    global:
        - GRADLE_OPTS='-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false'
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
before_install:
    - export TERM=dumb # to get clean gradle output
    - cp gradle.properties{.sample,}
    - mkdir -p "$ANDROID_HOME"/licenses
    - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME"/licenses/android-sdk-license
script:
    - ./gradlew check
