# https://github.com/embarkmobile/android-maven-example
language: java
jdk: oraclejdk8
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - sudo apt-get install -qq libstdc++6:i386 lib32z1
    - export COMPONENTS=extra
    - curl -L https://raw.github.com/embarkmobile/android-sdk-installer/master/android-sdk-installer | bash /dev/stdin --install=$COMPONENTS
    - source ~/.android-sdk-installer/env
    - export TERM=dumb # to get clean gradle output
    - cp gradle.properties{.sample,}
    # Create and start emulator
    #- android list targets # for debugging
    #- echo no | android create avd --force -n test -t 1
    #- emulator -avd test -no-skin -no-audio -no-window &
    #- wait_for_emulator
script:
    - ./gradlew check
    #- ./gradlew connectedInstrumentTest
