language: android
jdk:
    - oraclejdk8
before_install:
    - export TERM=dumb # to get clean gradle output
    - cp gradle.properties{.sample,}
    - echo yes | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.1,android-22,extra-android-m2repository,extra-google-m2repository
script:
    - ./gradlew check
    #- ./gradlew connectedInstrumentTest
