sudo: false
language: android
jdk:
    - oraclejdk8
cache:
    directories:
        - $HOME/.m2
        - $HOME/.gradle
before_install:
    - export TERM=dumb # to get clean gradle output
    - cp gradle.properties{.sample,}
    - echo yes | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-23.0.2,android-23,extra-android-m2repository,extra-google-m2repository
script:
    - ./gradlew check
